// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StoreManagementSystem.Data;

#nullable disable

namespace StoreManagementSystem.Migrations
{
    [DbContext(typeof(StoreManagementSystemContext))]
    [Migration("20240704055453_AddUnitMigration")]
    partial class AddUnitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StoreManagementSystem.Models.Unit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Units");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTime(2024, 7, 4, 5, 54, 52, 337, DateTimeKind.Utc).AddTicks(8618),
                            Name = "Piece",
                            Symbol = "PCS",
                            UpdatedOn = new DateTime(2024, 7, 4, 5, 54, 52, 337, DateTimeKind.Utc).AddTicks(8621)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedOn = new DateTime(2024, 7, 4, 5, 54, 52, 337, DateTimeKind.Utc).AddTicks(8625),
                            Name = "Yards",
                            Symbol = "YDS",
                            UpdatedOn = new DateTime(2024, 7, 4, 5, 54, 52, 337, DateTimeKind.Utc).AddTicks(8625)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedOn = new DateTime(2024, 7, 4, 5, 54, 52, 337, DateTimeKind.Utc).AddTicks(8627),
                            Name = "Centimeter",
                            Symbol = "CM",
                            UpdatedOn = new DateTime(2024, 7, 4, 5, 54, 52, 337, DateTimeKind.Utc).AddTicks(8628)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedOn = new DateTime(2024, 7, 4, 5, 54, 52, 337, DateTimeKind.Utc).AddTicks(8629),
                            Name = "Milimeter",
                            Symbol = "MM",
                            UpdatedOn = new DateTime(2024, 7, 4, 5, 54, 52, 337, DateTimeKind.Utc).AddTicks(8630)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedOn = new DateTime(2024, 7, 4, 5, 54, 52, 337, DateTimeKind.Utc).AddTicks(8631),
                            Name = "Gauss",
                            Symbol = "GS",
                            UpdatedOn = new DateTime(2024, 7, 4, 5, 54, 52, 337, DateTimeKind.Utc).AddTicks(8632)
                        },
                        new
                        {
                            Id = 6L,
                            CreatedOn = new DateTime(2024, 7, 4, 5, 54, 52, 337, DateTimeKind.Utc).AddTicks(8633),
                            Name = "Cone",
                            Symbol = "Cone",
                            UpdatedOn = new DateTime(2024, 7, 4, 5, 54, 52, 337, DateTimeKind.Utc).AddTicks(8634)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
